"""add sop process statuses

Revision ID: 0aa451b79c43
Revises: b7e2587c18f6
Create Date: 2026-09-07 11:49:33.281576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa451b79c43'
down_revision: Union[str, Sequence[str], None] = 'b7e2587c18f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_process_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('process_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['legal_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['account_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'assessment_id', 'process_index', name='uq_sop_process_status')
    )
    op.create_index(op.f('ix_sop_process_statuses_id'), 'sop_process_statuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_process_statuses_id'), table_name='sop_process_statuses')
    op.drop_table('sop_process_statuses')
    # ### end Alembic commands ###
