"""add mapped_org_types to legal_assessments

Revision ID: 0f37d9fafe37
Revises: 662d8a21902e
Create Date: 2026-09-05 15:55:08.806671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f37d9fafe37'
down_revision: Union[str, Sequence[str], None] = '662d8a21902e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_assessments', sa.Column('mapped_org_types', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_assessments', 'mapped_org_types')
    # ### end Alembic commands ###
