"""add training module and notifications tables

Revision ID: 1d1c35bb3a65
Revises: d4e9f2a7c1b3
Create Date: 2026-09-18 13:03:00.787900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1c35bb3a65'
down_revision: Union[str, Sequence[str], None] = 'd4e9f2a7c1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_audit_log_id'), 'training_audit_log', ['id'], unique=False)
    op.create_table('training_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_roles', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['super_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_courses_act_code'), 'training_courses', ['act_code'], unique=False)
    op.create_index(op.f('ix_training_courses_id'), 'training_courses', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_admin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_admin_id'], ['account_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_admin_id'), 'notifications', ['recipient_admin_id'], unique=False)
    op.create_table('training_course_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'account_id', 'role_id', name='uq_training_allocation_course_account_role')
    )
    op.create_index(op.f('ix_training_course_allocations_id'), 'training_course_allocations', ['id'], unique=False)
    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('department_item_id', sa.Integer(), nullable=True),
    sa.Column('process_item_id', sa.Integer(), nullable=True),
    sa.Column('test_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_item_id'], ['master_registry_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_item_id'], ['master_registry_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_modules_id'), 'training_modules', ['id'], unique=False)
    op.create_table('training_content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_content_items_id'), 'training_content_items', ['id'], unique=False)
    op.create_table('training_content_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['account_admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['training_content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'content_item_id', name='uq_training_progress_admin_content')
    )
    op.create_index(op.f('ix_training_content_progress_id'), 'training_content_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_content_progress_id'), table_name='training_content_progress')
    op.drop_table('training_content_progress')
    op.drop_index(op.f('ix_training_content_items_id'), table_name='training_content_items')
    op.drop_table('training_content_items')
    op.drop_index(op.f('ix_training_modules_id'), table_name='training_modules')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_training_course_allocations_id'), table_name='training_course_allocations')
    op.drop_table('training_course_allocations')
    op.drop_index(op.f('ix_notifications_recipient_admin_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_training_courses_id'), table_name='training_courses')
    op.drop_index(op.f('ix_training_courses_act_code'), table_name='training_courses')
    op.drop_table('training_courses')
    op.drop_index(op.f('ix_training_audit_log_id'), table_name='training_audit_log')
    op.drop_table('training_audit_log')
    # ### end Alembic commands ###
