"""add chapter and rules text fields to training modules

Revision ID: 2479f1ebd9d2
Revises: c7a795e3b32d
Create Date: 2026-09-18 18:36:06.385074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2479f1ebd9d2'
down_revision: Union[str, Sequence[str], None] = 'c7a795e3b32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_modules', sa.Column('chapter', sa.String(length=255), nullable=True))
    op.add_column('training_modules', sa.Column('rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_modules', 'rules')
    op.drop_column('training_modules', 'chapter')
    # ### end Alembic commands ###
