"""add training assignments questions attempts

Revision ID: 39ce72f66f96
Revises: 2479f1ebd9d2
Create Date: 2026-09-19 14:17:43.847784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ce72f66f96'
down_revision: Union[str, Sequence[str], None] = '2479f1ebd9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_assignments_id'), 'training_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_training_assignments_module_id'), 'training_assignments', ['module_id'], unique=False)
    op.create_table('training_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('marks_obtained', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['account_admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignment_id'], ['training_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_attempts_admin_id'), 'training_attempts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_training_attempts_assignment_id'), 'training_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_training_attempts_id'), 'training_attempts', ['id'], unique=False)
    op.create_table('training_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=10), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['training_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_questions_assignment_id'), 'training_questions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_training_questions_id'), 'training_questions', ['id'], unique=False)
    op.create_table('training_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_training_answer_attempt_question')
    )
    op.create_index(op.f('ix_training_attempt_answers_attempt_id'), 'training_attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_training_attempt_answers_id'), 'training_attempt_answers', ['id'], unique=False)
    op.create_table('training_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['training_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_question_options_id'), 'training_question_options', ['id'], unique=False)
    op.create_index(op.f('ix_training_question_options_question_id'), 'training_question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_question_options_question_id'), table_name='training_question_options')
    op.drop_index(op.f('ix_training_question_options_id'), table_name='training_question_options')
    op.drop_table('training_question_options')
    op.drop_index(op.f('ix_training_attempt_answers_id'), table_name='training_attempt_answers')
    op.drop_index(op.f('ix_training_attempt_answers_attempt_id'), table_name='training_attempt_answers')
    op.drop_table('training_attempt_answers')
    op.drop_index(op.f('ix_training_questions_id'), table_name='training_questions')
    op.drop_index(op.f('ix_training_questions_assignment_id'), table_name='training_questions')
    op.drop_table('training_questions')
    op.drop_index(op.f('ix_training_attempts_id'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_assignment_id'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_admin_id'), table_name='training_attempts')
    op.drop_table('training_attempts')
    op.drop_index(op.f('ix_training_assignments_module_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_id'), table_name='training_assignments')
    op.drop_table('training_assignments')
    # ### end Alembic commands ###
