"""add readiness response tracking and submissions

Revision ID: 662d8a21902e
Revises: b581980db44f
Create Date: 2026-09-04 21:14:33.755179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662d8a21902e'
down_revision: Union[str, Sequence[str], None] = 'b581980db44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('act_code', sa.String(length=100), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['account_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'act_code', name='uq_readiness_submission_account_act')
    )
    op.create_index(op.f('ix_readiness_submissions_id'), 'readiness_submissions', ['id'], unique=False)
    op.add_column('question_assignments', sa.Column('response', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_assignments', 'response')
    op.drop_index(op.f('ix_readiness_submissions_id'), table_name='readiness_submissions')
    op.drop_table('readiness_submissions')
    # ### end Alembic commands ###
