"""remove manual user industry and process profile fields

Revision ID: 72278a6cf5c3
Revises: e008a3ce7f67
Create Date: 2026-09-02 14:42:25.037036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72278a6cf5c3'
down_revision: Union[str, Sequence[str], None] = 'e008a3ce7f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_processes_id'), table_name='account_user_processes')
    op.drop_table('account_user_processes')
    op.drop_column('account_admins', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_admins', sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('account_user_processes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_admin_id'], ['account_admins.id'], name=op.f('account_user_processes_account_admin_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_user_processes_pkey'))
    )
    op.create_index(op.f('ix_account_user_processes_id'), 'account_user_processes', ['id'], unique=False)
    # ### end Alembic commands ###
