"""add roles and account_admin login fields

Revision ID: 83dbdd5deef7
Revises: 96ad54d494e5
Create Date: 2026-09-01 18:30:52.923929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83dbdd5deef7'
down_revision: Union[str, Sequence[str], None] = '96ad54d494e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('account_admins', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('account_admins', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('account_admins', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('account_admins', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_account_admins_role_id_roles', 'account_admins', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('fk_account_admins_created_by_account_admins', 'account_admins', 'account_admins', ['created_by'], ['id'])
    # ### end Alembic commands ###

    roles_table = sa.table('roles', sa.column('id', sa.Integer), sa.column('role_name', sa.String), sa.column('description', sa.Text))
    conn = op.get_bind()
    conn.execute(roles_table.insert().values([
        {'role_name': 'Account Admin', 'description': 'Full access to their account\'s portal; can create and manage Users.'},
        {'role_name': 'User', 'description': 'Scoped access to assigned process areas; cannot manage other users.'},
    ]))
    account_admin_role_id = conn.execute(sa.text("SELECT id FROM roles WHERE role_name = 'Account Admin'")).scalar()
    conn.execute(sa.text(
        "UPDATE account_admins SET role_id = :role_id, is_active = TRUE WHERE role_id IS NULL"
    ), {"role_id": account_admin_role_id})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_account_admins_created_by_account_admins', 'account_admins', type_='foreignkey')
    op.drop_constraint('fk_account_admins_role_id_roles', 'account_admins', type_='foreignkey')
    op.drop_column('account_admins', 'last_login_at')
    op.drop_column('account_admins', 'created_by')
    op.drop_column('account_admins', 'is_active')
    op.drop_column('account_admins', 'role_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
