"""baseline

Revision ID: 96ad54d494e5
Revises: 
Create Date: 2026-08-30 19:20:37.992665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ad54d494e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_compliance_sections_id'), 'compliance_sections', ['id'], unique=False)
    op.create_table('enterprise_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=255), nullable=False),
    sa.Column('project_start_date', sa.Date(), nullable=False),
    sa.Column('project_end_date', sa.Date(), nullable=False),
    sa.Column('tracking_start_date', sa.Date(), nullable=False),
    sa.Column('tracking_end_date', sa.Date(), nullable=False),
    sa.Column('ceo_name', sa.String(length=255), nullable=False),
    sa.Column('ceo_phone', sa.String(length=50), nullable=False),
    sa.Column('contact_person_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code')
    )
    op.create_index(op.f('ix_enterprise_accounts_id'), 'enterprise_accounts', ['id'], unique=False)
    op.create_table('legal_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_chapters_act_code'), 'legal_chapters', ['act_code'], unique=False)
    op.create_index(op.f('ix_legal_chapters_id'), 'legal_chapters', ['id'], unique=False)
    op.create_table('master_registries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_key')
    )
    op.create_index(op.f('ix_master_registries_id'), 'master_registries', ['id'], unique=False)
    op.create_table('resources_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mapped_acts', sa.Text(), nullable=True),
    sa.Column('mapped_industry_processes', sa.Text(), nullable=True),
    sa.Column('mapped_industries', sa.Text(), nullable=True),
    sa.Column('mapped_org_types', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_documents_id'), 'resources_documents', ['id'], unique=False)
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    op.create_table('account_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('admin_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_admins_id'), 'account_admins', ['id'], unique=False)
    op.create_table('account_enrolled_acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('act_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_enrolled_acts_id'), 'account_enrolled_acts', ['id'], unique=False)
    op.create_table('legal_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('rule_order', sa.Integer(), nullable=True),
    sa.Column('rule_narrative', sa.Text(), nullable=False),
    sa.Column('sample_policies', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['legal_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_rules_id'), 'legal_rules', ['id'], unique=False)
    op.create_table('master_registry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['master_registries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_registry_items_id'), 'master_registry_items', ['id'], unique=False)
    op.create_table('legal_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('section_explanation', sa.Text(), nullable=False),
    sa.Column('practical_examples', sa.Text(), nullable=True),
    sa.Column('mapped_acts', sa.Text(), nullable=True),
    sa.Column('sub_sections', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['legal_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_sections_id'), 'legal_sections', ['id'], unique=False)
    op.create_table('legal_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('mapped_acts', sa.Text(), nullable=True),
    sa.Column('industries', sa.Text(), nullable=True),
    sa.Column('industry_process', sa.String(length=255), nullable=False),
    sa.Column('sop_name', sa.String(length=255), nullable=False),
    sa.Column('sop_details', sa.Text(), nullable=False),
    sa.Column('processes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['legal_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_assessments_id'), 'legal_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_assessments_id'), table_name='legal_assessments')
    op.drop_table('legal_assessments')
    op.drop_index(op.f('ix_legal_sections_id'), table_name='legal_sections')
    op.drop_table('legal_sections')
    op.drop_index(op.f('ix_master_registry_items_id'), table_name='master_registry_items')
    op.drop_table('master_registry_items')
    op.drop_index(op.f('ix_legal_rules_id'), table_name='legal_rules')
    op.drop_table('legal_rules')
    op.drop_index(op.f('ix_account_enrolled_acts_id'), table_name='account_enrolled_acts')
    op.drop_table('account_enrolled_acts')
    op.drop_index(op.f('ix_account_admins_id'), table_name='account_admins')
    op.drop_table('account_admins')
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_resources_documents_id'), table_name='resources_documents')
    op.drop_table('resources_documents')
    op.drop_index(op.f('ix_master_registries_id'), table_name='master_registries')
    op.drop_table('master_registries')
    op.drop_index(op.f('ix_legal_chapters_id'), table_name='legal_chapters')
    op.drop_index(op.f('ix_legal_chapters_act_code'), table_name='legal_chapters')
    op.drop_table('legal_chapters')
    op.drop_index(op.f('ix_enterprise_accounts_id'), table_name='enterprise_accounts')
    op.drop_table('enterprise_accounts')
    op.drop_index(op.f('ix_compliance_sections_id'), table_name='compliance_sections')
    op.drop_table('compliance_sections')
    # ### end Alembic commands ###
