"""add sop status, activities and files tables

Revision ID: b7e2587c18f6
Revises: f8839f9284fd
Create Date: 2026-09-06 22:48:57.022026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e2587c18f6'
down_revision: Union[str, Sequence[str], None] = 'f8839f9284fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['legal_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['account_admins.id'], ),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['account_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_activities_id'), 'sop_activities', ['id'], unique=False)
    op.create_table('sop_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['legal_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['account_admins.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['account_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_files_id'), 'sop_files', ['id'], unique=False)
    op.create_table('sop_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['legal_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['account_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'assessment_id', name='uq_sop_status_account_assessment')
    )
    op.create_index(op.f('ix_sop_statuses_id'), 'sop_statuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_statuses_id'), table_name='sop_statuses')
    op.drop_table('sop_statuses')
    op.drop_index(op.f('ix_sop_files_id'), table_name='sop_files')
    op.drop_table('sop_files')
    op.drop_index(op.f('ix_sop_activities_id'), table_name='sop_activities')
    op.drop_table('sop_activities')
    # ### end Alembic commands ###
