"""add account enabled tabs

Revision ID: c5d01260d3b3
Revises: a41c7d90e5b2
Create Date: 2026-09-19 18:16:21.937679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d01260d3b3'
down_revision: Union[str, Sequence[str], None] = 'a41c7d90e5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_enabled_tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tab_key', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'tab_key', name='uq_account_enabled_tab')
    )
    op.create_index(op.f('ix_account_enabled_tabs_account_id'), 'account_enabled_tabs', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_enabled_tabs_id'), 'account_enabled_tabs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_enabled_tabs_id'), table_name='account_enabled_tabs')
    op.drop_index(op.f('ix_account_enabled_tabs_account_id'), table_name='account_enabled_tabs')
    op.drop_table('account_enabled_tabs')
    # ### end Alembic commands ###
