"""add description to training content items

Revision ID: c7a795e3b32d
Revises: 4fd84b3564cc
Create Date: 2026-09-18 17:24:27.232280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a795e3b32d'
down_revision: Union[str, Sequence[str], None] = '4fd84b3564cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_content_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_content_items', 'description')
    # ### end Alembic commands ###
