"""add user provisioning fields and question assignments

Revision ID: e008a3ce7f67
Revises: 83dbdd5deef7
Create Date: 2026-09-02 13:19:56.604364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e008a3ce7f67'
down_revision: Union[str, Sequence[str], None] = '83dbdd5deef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_admin_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_admin_id'], ['account_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_processes_id'), 'account_user_processes', ['id'], unique=False)
    op.create_table('question_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['enterprise_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['legal_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['account_admins.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['account_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'assessment_id', name='uq_question_assignment_account_assessment')
    )
    op.create_index(op.f('ix_question_assignments_id'), 'question_assignments', ['id'], unique=False)
    op.add_column('account_admins', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('account_admins', sa.Column('role_description', sa.Text(), nullable=True))
    op.add_column('account_admins', sa.Column('industry', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_admins', 'industry')
    op.drop_column('account_admins', 'role_description')
    op.drop_column('account_admins', 'job_title')
    op.drop_index(op.f('ix_question_assignments_id'), table_name='question_assignments')
    op.drop_table('question_assignments')
    op.drop_index(op.f('ix_account_user_processes_id'), table_name='account_user_processes')
    op.drop_table('account_user_processes')
    # ### end Alembic commands ###
